2022-12-08 09:18:37.125935: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-12-08 09:18:37.125977: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "top_run.py", line 3, in <module>
    import models.bert_hier
  File "/home/andy/projects/data_loader/python/models/bert_hier.py", line 1, in <module>
    from transformers.models.bert.modeling_bert import BertPreTrainedModel, BertEncoder
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/__init__.py", line 19, in <module>
    from . import (
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/layoutlm/__init__.py", line 22, in <module>
    from .configuration_layoutlm import LAYOUTLM_PRETRAINED_CONFIG_ARCHIVE_MAP, LayoutLMConfig
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/layoutlm/configuration_layoutlm.py", line 19, in <module>
    from ..bert.configuration_bert import BertConfig
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/bert/configuration_bert.py", line 21, in <module>
    from ...onnx import OnnxConfig
  File "/usr/local/lib/python3.8/dist-packages/transformers/onnx/__init__.py", line 17, in <module>
    from .convert import export, validate_model_outputs
  File "/usr/local/lib/python3.8/dist-packages/transformers/onnx/convert.py", line 23, in <module>
    from .. import PreTrainedModel, PreTrainedTokenizer, TensorType, TFPreTrainedModel, is_torch_available
  File "<frozen importlib._bootstrap>", line 1039, in _handle_fromlist
  File "/usr/local/lib/python3.8/dist-packages/transformers/file_utils.py", line 1984, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/usr/local/lib/python3.8/dist-packages/transformers/file_utils.py", line 1993, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.8/dist-packages/transformers/modeling_tf_utils.py", line 27, in <module>
    import tensorflow as tf
  File "/home/andy/.local/lib/python3.8/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/andy/.local/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python.feature_column import feature_column_lib as feature_column
  File "/home/andy/.local/lib/python3.8/site-packages/tensorflow/python/feature_column/feature_column_lib.py", line 22, in <module>
    from tensorflow.python.feature_column.feature_column import *
  File "/home/andy/.local/lib/python3.8/site-packages/tensorflow/python/feature_column/feature_column.py", line 147, in <module>
    from tensorflow.python.layers import base
  File "/home/andy/.local/lib/python3.8/site-packages/tensorflow/python/layers/base.py", line 20, in <module>
    from tensorflow.python.keras.legacy_tf_layers import base
  File "/home/andy/.local/lib/python3.8/site-packages/tensorflow/python/keras/__init__.py", line 25, in <module>
    from tensorflow.python.keras import models
  File "/home/andy/.local/lib/python3.8/site-packages/tensorflow/python/keras/models.py", line 20, in <module>
    from tensorflow.python.keras import metrics as metrics_module
  File "/home/andy/.local/lib/python3.8/site-packages/tensorflow/python/keras/metrics.py", line 34, in <module>
    from tensorflow.python.keras import activations
  File "/home/andy/.local/lib/python3.8/site-packages/tensorflow/python/keras/activations.py", line 18, in <module>
    from tensorflow.python.keras.layers import advanced_activations
  File "/home/andy/.local/lib/python3.8/site-packages/tensorflow/python/keras/layers/__init__.py", line 22, in <module>
    from tensorflow.python.keras.engine.input_layer import Input
  File "/home/andy/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/input_layer.py", line 24, in <module>
    from tensorflow.python.keras.engine import base_layer
  File "/home/andy/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 54, in <module>
    from tensorflow.python.keras.mixed_precision import loss_scale_optimizer
  File "/home/andy/.local/lib/python3.8/site-packages/tensorflow/python/keras/mixed_precision/loss_scale_optimizer.py", line 28, in <module>
    from tensorflow.python.keras import optimizers
  File "/home/andy/.local/lib/python3.8/site-packages/tensorflow/python/keras/optimizers.py", line 24, in <module>
    from tensorflow.python.keras.optimizer_v2 import adadelta as adadelta_v2
  File "/home/andy/.local/lib/python3.8/site-packages/tensorflow/python/keras/optimizer_v2/adadelta.py", line 22, in <module>
    from tensorflow.python.keras.optimizer_v2 import optimizer_v2
  File "/home/andy/.local/lib/python3.8/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py", line 115, in <module>
    class OptimizerV2(trackable.Trackable):
  File "/home/andy/.local/lib/python3.8/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py", line 1326, in OptimizerV2
    def _dense_apply_args(self):
  File "/home/andy/.local/lib/python3.8/site-packages/tensorflow/python/keras/utils/layer_utils.py", line 407, in cached_per_instance
    def wrapped(item):
  File "/usr/lib/python3.8/functools.py", line 51, in update_wrapper
    value = getattr(wrapped, attr)
KeyboardInterrupt
